@startuml

'Rearrange the order of members in all objects
'skinparam classAttributeOrder constructor, attribute, method

'Run the generated PlantUML diagram
!include diagram.plantuml

'Hides the "separator" lines when it's empty
hide empty members

'Remove unnecessary objects
remove HelloWorld
remove PlayerControllerTest
remove ExampleIT
remove ExampleTest
remove Main

'Remove package-info files
remove node0
remove node1
remove node18

'Force rearrange objects
'WorldModel -[hidden]-- WorldView
'Player -[hidden]- WorldModel
'Player -[hidden] Actor

'SIMPLE LAYOUT (no dependencies)
'WorldModel - WorldBoard
'WorldModel -- GameState
'WorldModel -- EnemyFactory
'Size -- Transform


@enduml
