@startuml

'Rearrange the order of members in all objects
'skinparam classAttributeOrder constructor, attribute, method

'force vertical/horizontal lines
skinparam linetype ortho

'Run the generated PlantUML diagram
!include diagram.plantuml

'Hides the "separator" lines when it's empty
hide empty members

'Remove unnecessary objects
remove HelloWorld
remove PlayerControllerTest
remove ExampleIT
remove ExampleTest
remove Main
remove CoinTest
remove CollisionBoxTest
remove EnemyFactory
remove EnemyFactoryTest
remove EnemyTest
remove fixedObjectTest
remove GameStateTest
remove MobileObjectTest
remove PlayerTest
remove PositionTest
remove WorldBoardTest
remove FixedObjectTest
remove ControllerTest

'Remove package-info files
remove node21
remove node22
remove node31

'Force rearrange objects
'WorldModel -[hidden]-- WorldView
'Player -[hidden]- WorldModel
'Player -[hidden] Actor

'SIMPLE LAYOUT (no dependencies)
'WorldModel - WorldBoard
'WorldModel -- GameState
'WorldModel -- EnemyFactory
'Size -- Transform

'ARROW THICKNESS
' - Manually add thickness=4 to each relation in diagram.plantuml.

@enduml
