@startuml

'Rearrange the order of members in all objects
'skinparam classAttributeOrder constructor, attribute, method

'force vertical/horizontal lines
skinparam linetype ortho

'Run the generated PlantUML diagram
!include diagram.plantuml

'Hides the "separator" lines when it's empty
hide empty members

'Remove guaranteed unnecessary objects
remove HelloWorld
remove PlayerControllerTest
remove ExampleIT
remove ExampleTest
remove Main
remove CoinTest
remove CollisionBoxTest
remove EnemyFactory
remove EnemyFactoryTest
remove EnemyTest
remove fixedObjectTest
remove GameStateTest
remove MobileObjectTest
remove PlayerTest
remove PositionTest
remove WorldBoardTest
remove FixedObjectTest
remove ControllerTest
remove ModelTest
remove MushroomTest
remove PlayerAnimation
remove SoundHandlerTest
remove ItemFactoryTest
remove WorldModelTest
remove BananaTest
remove ViewTest
remove EnemyType
remove ItemFactory
Remove MainTest
remove Pair
remove PlayerAnimationTest
remove WorldViewTest
remove ParallaxBackgroundTest
remove TransformTest
remove LevelManagerTest
remove CollisionHandlerTest


'Remove potentially unnecessary objects
remove Direction
remove LevelManager
remove SoundHandler
remove ParallaxBackground
remove WorldBoard
remove Scorable
remove CollisionHandler
remove GameState

'Remove package-info files
remove node26
remove node33
remove node43

'Force rearrange objects
'WorldModel -[hidden]-- WorldView
'Player -[hidden]- WorldModel
'Player -[hidden] Actor

'SIMPLE LAYOUT (no dependencies)
'WorldModel - WorldBoard
'WorldModel -- GameState
'WorldModel -- EnemyFactory
'Size -- Transform

'ARROW THICKNESS
' - Manually add thickness=4 to each relation in diagram.plantuml.

@enduml
